version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose the server on port 8080
    volumes:
      - ./backend:/app # Mount the backend folder for live updates (optional)
    command: ["node", "server.js"] # Start the server
